name: Upload And Download

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  upload-gradle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-all.zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: gradle-8.7
          name: Gradle 8.7
          draft: false
          prerelease: false
          files: gradle-8.7-all.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
